# Generated by Django 4.2 on 2025-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_Type',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('vendor', 'vendor')], default=None, max_length=255, null=True),
        ),
    ]
