# Generated by Django 4.2 on 2025-06-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_Type',
        ),
    ]
