# Generated by Django 4.2 on 2025-06-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_remove_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-user.jpg', null=True, upload_to='images'),
        ),
    ]
