# Generated by Django 4.2 on 2025-06-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_gallery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendors',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
