# Generated by Django 4.2 on 2025-06-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_vendors_remove_orderitem_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bank_receipt',
            field=models.FileField(blank=True, null=True, upload_to='bank_receipts/'),
        ),
    ]
