# Generated by Django 4.2 on 2025-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_bank_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('Flutterwave', 'Flutterwave'), ('Paystack', 'Paystack')], default=None, max_length=100, null=True),
        ),
    ]
